myblog/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index), #尤其注意路径最后加上/和$
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page,name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page,name='edit_page'),
    url(r'^edit/action$', views.edit_action,name='edit_action'),
]

myblog/blog22/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index), #尤其注意路径最后加上/和$
]

myblog/myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog')), #总路径，尤其注意/
    url(r'^blog22/', include('blog22.urls')),
]

myblog/blog/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=32,default='title')
    content = models.TextField(null=True)

    def __str__(self):
        return self.title

myblog/blog22/models.py
from django.db import models

# Create your models here.

myblog/blog/views.py
from django.shortcuts import render #render:渲染
from django.http import HttpResponse
from . import models
# Create your views here.
def index(request):
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})       #HttpResponse('hello world!')
#{'hello':'hello wonderful world! guess why是噢简单'}#可以作为第三个参数
def article_page(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{'article':article})
def edit_page(request,article_id):
    if str(article_id)=='0':
        return render(request,'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request,'blog/edit_page.html',{'article':article})
def edit_action(request):
    title = request.POST.get('title','TITLE')
    content = request.POST.get('content','CONTENT')
    article_id = request.POST.get('article_id','0')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request,'blog/index.html',{'articles':articles})
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content=content
    article.save()
    return render(request,'blog/article_page.html',{'article':article})

myblog/blog22/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'blog22/index.html')

myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{article.title}}</h1>
<br/>
<h3>{{article.content}}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    {% if article %}
        <input type="hidden" name="article_id" value="{{ article.id }}"/>
        <label>文章标题
            <input type="text" name="title" value="{{ article.title }}"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{ article.content }}"/>
        </label>
        <br/>
    {% else %}
        <input type="hidden" name="article_id" value="0"/>
        <label>文章标题
            <input type="text" name="title"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content"/>
        </label>
        <br/>
    {% endif %}
    <input type="submit" value="点击提交">
</form>
</body>
</html>

myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django is funny</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">新文章</a>
</h1>
<h2>
{%for article in articles%}
    <a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
    <br/>
{%endfor%}
</h2>
</body>
</html>

myblog/blog22/templates/blog22/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django is funny@@@@</title>
</head>
<body>
<h1> hello,blog222222222222</h1>
</body>
</html>